TeamMODOO/FE

package.json
src/app/page.tsx
src/components/index.ts
src/components/modal/enter-meeting_room/enter-meeting_room.tsx
src/components/modal/enter-meeting_room/pagination.tsx
src/components/modal/enter-meeting_room/room.tsx
src/components/ui/dialog.tsx
src/components/ui/label.tsx
src/components/ui/pagination.tsx
yarn.lock

- close #8 
- 회의실 접근 모달 띄우기
- 모달 안에 컨텐츠 구현

💄 Design(#8): 회의실 접근 모달 구현 

---

src/app/lobby/_component/Canvas.tsx
src/app/lobby/_component/CharacterArray.tsx
src/hooks/useThrottle.tsx

- close #7 
* w, a, s, d 입력으로 캐릭터 상하좌우 움직임 구현 
* 좌, 우 이동시 캐릭터 좌우 반전하여 화면에 랜더링
* Throttle을 이용하여 움직임에 delay 추가
* 정글러2가 현재 플레이어 캐릭터일때 우측 움직임
* 정글러2가 현재 플레이어 캐릭터일때 좌측 움직임
* 충돌처리 로직 구현 논의 필요
* 캐릭터 이동시 애니메이션 효과에 대한 논의 필요

Feat(#7):키보드 입력을 통한 로비에서 캐릭터 이동 기능 구현

---

src/app/lobby/page.tsx
src/app/page.tsx
src/components/chat/lobby/chatMessages.tsx
src/components/chat/lobby/listMessages.tsx
src/components/chat/message.tsx
src/hooks/useChatScroll.tsx
src/hooks/useChatSocket.tsx
src/hooks/useMainSocketConnect.tsx
src/model/chatting.ts

✨ Feat(#34): 서버와 소켓 연결

---

src/app/lobby/_component/Canvas/Canvas.tsx
src/app/lobby/page.tsx
src/hooks/useMainSocketConnect.tsx
src/hooks/useMovementSocket.tsx
src/store/useUsersStore.tsx

- close #38 
* socket.io 라이브러리를 이용해 캐릭터 이동 로직을 지정된 프로토콜에 맞게 구현
* 유저 움직임 코드 최적화
* 유저들의 위치 정보들을 state에서 ref로 저장하도록 변경
* 기존 로직은 state가 업데이트 될때마다 + 30fps 마다 업데이트가 됨
* 변경한 로직은 ref 형태로 값을 저장하기 때문에 30fps때만 업데이트가 됨
* 브라우저 활성화 시간과 내부 시스템 타이머인 setInterval와 간격이 있어 사이 시간동안 흰 화면이 깜빡임
* requestAnimationFrame 함수로 사용자들을 그리는 로직을 분리하여, 맵을 그린 직후에 호출하여 부드럽게 구현
* deltaTime으로 30fps로 시간차 계산 초기화

✨ Feat(#38): 캐릭터 이동 로직을 서버와 소켓 연결로 구현

---

src/hooks/useMainSocketConnect.tsx

- close #이슈번호 
- 소켓 연결 시 baseURL 변경
- .env 파일에 백엔드 서버 저장

🔨 Refactor(#48): 소켓 url 변경"

---

package.json
src/app/api/portfolio/route.ts
src/app/lobby/_component/Canvas/Canvas.tsx
src/app/myroom/[id]/_component/Canvas/Canvas.tsx
src/hooks/useChatSocket.tsx
src/hooks/useMainSocketConnect.tsx
src/hooks/useMyRoomSocketEvents.ts
yarn.lock

- close #51 
* 변경된 캐릭터 움직임 로직이 소켓을 통해 정상적으로 Echo 되는지 확인
* 백엔드 통신 규격에 맞춰 일부 코드를 수정
* uuid 라이브러리를 설치하고, 사용자별 고유 uuid를 로컬 스토리지에 저장해 소켓 연결에서 사용하도록 로직 수정
* 마이룸 이동 로직에 useThrottle을 적용해 딜레이를 추가
* 마이룸 포트폴리오 추가 모달에서 “저장” 시 S3 서버로 업로드되도록 로직 변경

✨ Feat(#51): 백엔드와 움직임 소켓 연결

---

src/app/questmap/QuestMap.module.css
src/app/questmap/_component/RankingModal/RankingModal.module.css
src/app/questmap/_component/RankingModal/RankingModal.tsx
src/app/questmap/page.tsx

- close #56  
- `/questmap` 에서 NPC 클릭 시 [오늘의 랭킹] 모달 출력
- 현재 더미데이터로 진행
- 희원님 작성하기 편하시도록 화면에 NPC 지워뒀습니다. (주석 처리)
주석 처리 된 부분들 지우고 작업 진행하시면 되겠습니다.

✨ Feat(#56): /questmap 순위 출력 기능 NPC 모달 기능 작업

---

src/app/api/check-answer/route.ts

- close #60 
- 수정 전: 정답 코드인 경우, '이렇게도 풀 수 있어요' 칸에 다른 솔루션이 나오지 않는 버그 발생
- `src/app/api/check-answer/route.ts` 내 프롬프트를 보완해 해결

🔨 Refactor(#60): 백준 문제풀이 채점 프롬프트 보완

---

src/app/myroom/[id]/_component/Canvas/Canvas.tsx
src/app/questmap/_component/Npc/NpcList.style.ts
src/app/questmap/_component/Npc/NpcList.tsx
src/app/questmap/_component/Npc/NpcModal.style.ts
src/app/questmap/_component/Npc/NpcModal.tsx
src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.style.ts
src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx
src/app/questmap/_model/User.ts
src/app/questmap/page.tsx
src/hooks/useQuestMapSocketEvents.ts

- close #57 
* 퀘스트 맵 구현
* 퀘스트 맵에서의 움직임 구현
* 퀘스트 맵에서의 NPC, 포탈 구현
* 마이룸 포탈 구현
* 퀘스트 맵(이동, NPC, 포탈 구현)
* 마이룸 포탈 구현

✨ Feat(#57):  퀘스트 맵 및 움직임 구현

---

src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx

- close #69 
- `/questmap` 에서 `npc1`과 상호작용 시 문제풀이 랭킹 출력 모달 띄움

✨ Feat(#69): /questmap 에서 랭킹 출력 모달 띄우기

---

package.json
src/app/lobby/_component/Canvas/Canvas.tsx
src/app/lobby/_component/DailyProblem/DailyProblemContent.tsx
src/app/lobby/_component/MapConstants.ts
src/app/lobby/_component/enter-meeting_room/enter-meeting_room.tsx
src/app/lobby/_component/enter-meeting_room/room.tsx
yarn.lock

- close #68  
* 개발한 프론트엔드 페이지들 연결
* NPC 클릭시 /quest, /questmap으로 이동할 수 있도록 모달 구현
* 미팅룸 포탈에 들어가려 할 때 아래의 모달이 뜨도록 변경

✨ Feat(#68): 프론트엔드 각 페이지 연결

---

src/app/lobby/_component/Canvas/Canvas.tsx
src/app/lobby/_component/DailyProblem/DailyProblemContent.tsx
src/app/lobby/_component/Widget/Chatting.tsx
src/app/lobby/page.tsx
src/app/myroom/[id]/_component/Canvas/Canvas.tsx
src/app/myroom/[id]/_component/PortfolioModal/PdfViewerModal.tsx
src/app/myroom/[id]/_model/Funiture.ts

- close #80 
* 메인 로비에서 채팅 입력시 움직임 제한 로직 추가
* 마이룸 포트폴리오 조회시 Iframe으로 보이도록 로직 추가
* 메인 로비 백준 NPC 대사 수정
* 메인 로비 백준 NPC 대사 수정
* 마이룸 포트폴리오 조회시 Iframe으로 보이도록 로직 추가
* 메인 로비에서 채팅 입력시 움직임 제한 로직 추가

🚑️ Fix(#80): 메인 로비에서 채팅 입력시 움직임 제한 로직 추가 및 코드 개선

---

src/app/lobby/_component/Canvas/Canvas.tsx

✨ Feat(#66): MAP_CONSTANTS 추가

---

Dockerfile
src/app/api/portfolio/route.ts
src/app/signin/page.tsx

📦️ Chore(#85): 빌드 에러 해결

---

.dockerignore
Dockerfile

- close #97  
- `.dockerignore` 파일 추가
- `Dockerfile` 수정

Chore(#97) .dockerignore 파일 추가 및 Dockerfile 수정

---

src/app/lobby/_component/Canvas/Canvas.tsx
src/app/lobby/page.tsx
src/app/myroom/[id]/_component/Canvas/Canvas.tsx
src/app/myroom/[id]/page.tsx
src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx

🚑️ Fix(#100): 소켓 중복 연결 제거 

---

src/app/quest/Quest.module.css
src/app/quest/page.tsx

- close #102 
- 드래곤 이미지 로딩 때문에 `quest` 화면 입장 시 용이 안날아가는 버그 발생 -> 수정

🚑️ Fix(#102): 백준 문제풀이 화면에 이미지 로딩 후 애니메이션 보여지도록 수정

---

src/app/quest/Quest.module.css
src/app/quest/page.tsx

🚑️ Fix: 용 잔상 현상 해결

---

src/app/lobby/_component/Canvas/Canvas.tsx
src/app/myroom/[id]/_component/Canvas/Canvas.tsx
src/app/myroom/[id]/page.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersStore.tsx

- close #104 
* 로비에서 소켓 데이터를 바탕으로 UsersStore 상태 최신화
* 마이룸 페이지 이동 버그 수정
* 마이룸 움직임 버그 수정

✨ Feat(#104): 로비에서 소켓 데이터를 바탕으로 UsersStore 상태 최신화

---

src/app/lobby/_component/Canvas/Canvas.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersStore.tsx

- close #108 
* socket 통신시 id를 uuid 이용하여 패킷을 주고받도록 설정
* 추후에 패킷에 user_name 추가되면 화면에 user_name이 랜더링 되도록 설정하기

🚑️ Fix(#108): 움직임 부분 소켓 연결 버그 수정

---

src/app/lobby/_component/Widget/ChattingWidget.tsx
src/hooks/chat/useChatSocket.ts
src/lib/utils/date.ts
src/model/chatting.ts

- close #111 
- 로비 페이지 채팅 패킷 네이밍 수정
- 채팅 위젯 디자인 수정

🔨 Refactor(#111): 채팅 패킷 수정

---

src/app/quest/Quest.module.css
src/app/quest/page.tsx

- close #이슈번호 
- 용 로딩 오류 수정 후 버튼이 안눌리던 현상 해결

🚑️ Fix: 백준 문제 풀이 페이지 버튼이 안눌리는 버그 수정

---

src/app/lobby/_component/Canvas/Canvas.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersStore.tsx

- close #114 
* 메인 로비 소켓 프로토콜에 user_name 추가
* 캐릭터 아래에 user_name 혹은 Guest가 뜨도록 변경
* 캐릭터 아래에 user_name 혹은 Guest가 뜨도록 변경

🚑️ Fix(#114): 메인 로비 소켓 프로토콜에 user_name 추가

---

.dockerignore
Dockerfile
src/app/lobby/_component/Widget/ChattingWidget.tsx
src/hooks/chat/useChatSocket.ts
src/hooks/socket/useAudioSocketConnect.ts
src/lib/utils/date.ts
src/model/chatting.ts

🔨 Refactor(#111): RTC URL 변경

---

src/hooks/socket/useMainSocketConnect.ts

- close #122 
* 같은 화면에 user_name을 가져와 캐릭터 아래에 잘 표시되는 것을 확인 가능하다

✨ Feat(#122): 소켓 서버 프로토콜 변경에 따른 useMainSocketConnect 코드 변경

---

src/hooks/socket/useMainSocketConnect.ts

- close #126 
* 배포시 소켓 움직임 부분 닉네임 버그 수정
* 배포후 정상 작동하는지 확인하기

🚑️ Fix(#126): 배포시 소켓 움직임 부분 닉네임 버그 수정

---

src/hooks/socket/useMainSocketConnect.ts

- close #129 
* useMainSocketConnect 누락 코드 추가
- [ㅌ] useMainSocketConnect 누락 코드 추가

🚑️ Fix(#129): useMainSocketConnect 누락 코드 추가

---

src/hooks/signin/useSignInPost.ts

- close #이슈번호 
- `src/hooks/signin/useSignInPost.ts`에서 POST 요청을 보내기 위한 절대주소 (`https://api.jgtower.com`)를 `.env`로 보내고 이를 가져와 사용하도록 수정

🔨 Refactor: API 서버 baseURL 환경변수 추출

---

src/app/lobby/page.tsx
src/app/meetingroom/[id]/_components/Header.tsx
src/app/meetingroom/[id]/_components/LocalVideo.tsx
src/app/meetingroom/[id]/_components/PeerMedia.tsx
src/app/meetingroom/[id]/_components/RemoteMedia.tsx
src/app/meetingroom/[id]/_hook/useMediaDevices.ts
src/app/meetingroom/[id]/_hook/usePeerSocketEvent.ts
src/app/meetingroom/[id]/_hook/useRoom.ts
src/app/meetingroom/[id]/_hook/useWebRTC.ts
src/app/meetingroom/[id]/page.tsx
src/app/myroom/[id]/page.tsx
src/app/questmap/page.tsx
src/hooks/chat/useChatSocket.ts
src/hooks/socket/useMainSocketConnect.ts

- close #133  
- 페이지 이동 시 type, id 추가
- 미팅룸 리팩토링

✨ Feat(#133): 페이지 이동 시 소켓 처리

---

src/app/quest/_component/Problem/Problem.module.css
src/app/quest/_component/Problem/page.tsx
src/app/quest/_component/QuestSection/QuestSection.module.css
src/app/quest/_component/QuestSection/page.tsx
src/auth.ts
src/hooks/quest/useQuestGet.ts
src/hooks/quest/useQuestPost.ts
src/hooks/signin/useSignInPost.ts

✨ Feat(#137) 백준 문제풀이 API 작성

---

src/app/typing/_component/TypingCompleteModal/TypingCompleteModal.module.css
src/app/typing/_component/TypingCompleteModal/TypingCompleteModal.tsx
src/app/typing/page.tsx
src/app/typing/typing.module.css

- close #140  
- `/typing`으로 들어가면 코딩 타자 연습 (싱글 모드)를 실행하실 수 있습니다. (환경 변수 최신화 확인)

✨ Feat(#140): 타자 연습 싱글 모드 추가

---

src/app/lobby/_component/Widget/ChatInput.tsx
src/app/lobby/_component/Widget/ChattingWidget.tsx
src/app/meetingroom/[id]/_components/ChatWidget.tsx
src/components/ui/textarea.tsx
src/hooks/chat/useChatScroll.ts
src/hooks/chat/useChatSocket.ts

- close #이슈번호 
- 채팅 리스트 수정
- 채팅 인풋 수정
- 채팅 읽어도 알림 안사라지는 버그 해결
- 채팅 패킷 수정

🚑️ Fix(#134): 채팅 디자인 수정 및 버그 수정

---

src/app/api/check-answer/route.ts

- close #148 
- `/quest` 페이지에서 `chatGPT`가  Invalid JSON 을 응답하는 경우들 발생 (사용자 미입력 후 제출 시 등)
- 프롬프트를 JSON 형식을 강조하도록 수정 (특히, `{user code}`가 없어도 JSON으로 응답하도록 수정)

🚑️ Fix(#148): 백준 문제 풀이 후 Invalid JSON 오류 픽스

---

src/app/lobby/_component/Widget/ChatInput.tsx
src/app/meetingroom/[id]/_components/ChatWidget.tsx
src/app/meetingroom/[id]/page.tsx
src/hooks/chat/useChatSocket.ts

- close #150
- enter 눌렀을 때 채팅 보내기
- shift + enter 눌렀을 때 줄바꿈

✨ Feat(#150): enter 키 눌렀을 때 채팅 보내기

---

src/app/quest/_component/QuestSection/page.tsx
src/app/quest/utils/getRandomQuestNumber.ts
src/app/questmap/_component/RankingModal/RankingModal.tsx
src/hooks/questmap/useQuetMapModalGet.ts

- close #151 
- 당일 문제 번호 선택하는 함수 분리
- 백준 랭킹 출력 API 연결

✨ Feat(#151): 백준 랭킹 출력 API 연결

---

src/app/lobby/_constant/index.ts
src/app/myroom/[id]/_component/BoardModal/BoardModal.style.ts
src/app/myroom/[id]/_component/BoardModal/BoardModal.tsx
src/app/myroom/[id]/_constant/index.ts
src/hooks/myroom/useGuestBookPost.ts

- close #151 
-  Design: 마이룸 방명록 구성 수정
- Feat: 방명록 POST API 작성
- Rename: 메인 화면 게시판, 마이룸 방명록 Rename
- 마이룸 내 방명록
- 마이룸 방명록 오브젝트의 이름이 '방명록'으로 rename 된 것을 확인 가능
- 메인 페이지의 게시판 오브젝트의 이름이 '게시판'으로 rename 된 것을 확인 가능

✨ Feat(#155): 마이룸 방명록 API 작업(POST)

---

src/app/lobby/_component/Canvas/LobbyCanvas.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersStore.ts

- close #158 
* 예전 프로토콜대로 로비의 움직임 관련 소켓 코드가 설계되어 있었음
* 바뀐 프로토콜에 맞게 useLobbySocketEvents.ts 코드를 수정하고 useUsersStore에 선언한 함수에 맵핑시켜 동작하도록 함
* 소켓 연결이 끊겨 SC_LEAVE_USER 소켓 이벤트가 발생한다면 useUsersStore에 removeUser를 호출하여 화면에서 랜더링 되지 않도록 삭제

🚑️ Fix(#158): 소켓 프로토콜에 맞게 메인 로비 코드 수정

---

src/app/signinloading/page.tsx

- close #159 
- `/signinloading` 페이지에서 로그인 API `POST` 요청을 과다하게 보내는 문제 픽스

🚑️ Fix(#159): 로그인 시 API 요청 과다 문제 픽스

---

src/queries/myroom/usePatchMyRoomOwnerProfile.ts

- close #158 
* Patch API에 withCredentials 속성 추가

✨ Feat(#158): Patch API에 withCredentials 속성 추가

---

src/app/myroom/[google_id]/_component/BoardModal/BoardModal.tsx
src/hooks/myroom/useGuestBookGet.ts

✨ Feat(#163): 마이룸 방명록 API 작업 (GET)

---

src/app/myroom/[google_id]/_component/Canvas/MyRoomCanvas.tsx
src/app/myroom/[google_id]/_component/FurnitureInfoModal/FurnitureInfoModal.tsx
src/app/myroom/[google_id]/page.tsx

- close #170 
* 마이룸에서 get한 정보가 화면에 제대로 뜨지 않음
* pdf를 S3 -> 발급받은 url PATCH 하는 로직이 작동하지 않음(422 에러)
* 새로운 정보를 업데이트 하는 경우 기존 값에 덮어 씌워짐

🚑️ Fix(#170): 마이룸 api 표시 버그 수정

---

src/app/myroom/[google_id]/_component/Canvas/MyRoomCanvas.tsx
src/queries/myroom/usePatchMyRoomOwnerProfile.ts

- close #172 
* 이력서를 string[]에서 string으로 명세에 맞게 변경

🚑️ Fix(#172): 마이룸 이력서 PDF PATCH 오류 수정

---

src/app/lobby/_component/Canvas/LobbyCanvas.tsx
src/hooks/lobby/useLobbySocketEvents.ts

- close #174 
- 가만히 있는 사용자가 처음 들어온 사용자 입장에서 보이도록 정보를 받아오는 소켓 패킷 관련 코드 작성
- 새로고침등 재접속시 원래 있던 위치에 캐릭터가 잘 랜더링 되는지 확인 
- 3초 이상 소켓 연결이 끊기면 사용자가 화면에서 사라지는지 확인하기

✨ Feat(#174): 메인 로비에서 움직임 관련 소켓 추가 패킷 연결

---

src/app/Canvas/hooks/useCanvasEvents.ts
src/app/lobby/_component/EnterMeetingRoom/EnterMeetingRoom.tsx
src/app/lobby/_component/EnterMeetingRoom/Room.tsx
src/app/meetingroom/[id]/page.tsx
src/model/MeetingRoom.ts
src/queries/meetingroom/useMeetingRoom.ts
src/queries/meetingroom/useMeetingRoomCreate.ts

- close #177  
- 미팅룸 생성 API 연동
- 미팅룸 조회 API 연동
- 미팅룸 참여 API 연동
- 미팅룸 나가기 API 연동

✨ Feat(#177): 미팅룸 API 연결

---

src/app/lobby/_component/Canvas/LobbyCanvas.tsx
src/app/lobby/page.tsx
src/app/myroom/[google_id]/_component/Canvas/MyRoomCanvas.tsx
src/app/questmap/page.tsx

- close #183 
* 소켓 연결 ROOM_ID 변경
* 방명록, 게시판, 미팅룸 정보 get 요청이 상위 컴포넌트에서 요청 제한

🚑️ Fix(#183): 소켓 연결 ROOM_ID 변경, 방명록, 게시판, 미팅룸 정보 get 요청이 상위 컴포넌트에서 요청되지 않도록 제한 

---

package.json
src/app/Canvas/_component/ColorPanel.tsx
src/app/Canvas/_component/PenSizePanel.tsx
src/app/Canvas/_component/Toolbar.tsx
src/components/ui/slider.tsx
src/store/usePenColor.ts
yarn.lock

Feat(#185): 그림판 toolbar 폰트 조절 추가

---

src/middleware.ts

- close #이슈번호 
- 미들 웨어 오류 hotfix

🚑️ Fix(#188): [hotfix] middleware

---

src/middleware.ts

- close #188 
- hotfix
- `/`에서 `/signin` 리디렉션 끔
- 미들웨어 예외에 `/signin` 경로 추가

Fix(#188): [hotfix] middleware_re

---

package.json
src/app/signinloading/page.tsx
src/middleware.ts
yarn.lock

- close #192 
* 배포시 생기는 로그인, middleware 관련 문제 수정

🚑️ Fix(#192): 배포시 생기는 로그인 문제 수정

---

src/app/lobby/_component/Widget/FriendDoor.tsx
src/app/lobby/_component/Widget/FriendInformation.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/queries/lobby/useUserQuery.ts

- close #191  
- 유저 리스트 조회
- 소켓 정렬
- 문 디자인 수정

✨ Feat(#191): 실시간 유저 정보 조회

---

src/app/lobby/_components/EnterMeetingRoom/EnterMeetingRoom.tsx
src/app/lobby/_components/NoticeBoardModal/NoticeBoardModal.tsx
src/app/myroom/[google_id]/_components/BoardModal/BoardModal.tsx
src/app/quest/_components/QuestSection/QuestSection.module.css
src/app/quest/_components/QuestSection/page.tsx
src/components/modal/NeedSignIn/NeedSignInModal.module.css

- close #197  
- 방명록 작성, 게시판 작성 이용 불가
- 백준 문제 풀이는 가능 / 랭킹에 올라가지 않음 / 랭킹 조회는 가능
- 미팅룸 방 들어가기는 가능 / 생성은 불가
- 마이룸 
- (타인의 마이룸) 방명록 작성 
- 백준 문제 풀이 
- 회의실

✨ Feat(#197): 비회원 가용 기능에 맞게 각각 모달 처리

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_components/NoticeBoardModal/NoticeBoardModal.module.css
src/app/lobby/_components/NoticeBoardModal/NoticeBoardModal.tsx
src/app/lobby/_components/NoticeBoardModal/NoticeCreateForm.module.css
src/app/lobby/_components/NoticeBoardModal/NoticeCreateForm.tsx
src/app/lobby/_components/NoticeBoardModal/NoticeDetail.module.css
src/app/lobby/_components/NoticeBoardModal/NoticeDetail.tsx
src/app/lobby/_components/NoticeBoardModal/NoticeList.module.css
src/app/lobby/_components/NoticeBoardModal/NoticeList.tsx
src/app/quest/_components/Problem/Problem.module.css
src/app/quest/_components/QuestSection/QuestSection.module.css
src/app/questmap/_components/RankingModal/RankingModal.module.css
src/app/questmap/_components/RankingModal/RankingModal.tsx
src/components/modal/NeedSignIn/NeedSignInModal.module.css

- close #209 
- 작성 중...
- 작성 중...

💄 Design(#209) 모달 디자인 작업

---

src/app/meetingroom/[id]/_hook/canvas/useCanvasEvents.ts
src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts
src/app/meetingroom/[id]/page.tsx
src/provider/socket-provider.tsx

✨ Feat(#100): s3 요청 함수 추가

---

src/hooks/socket/useAudioSocketConnect.ts

🚑️ Fix:  url 변경

---

src/provider/socket-provider.tsx

🔨 Refactor: 새로고침 했을 때 소켓 연결 끊기

---

src/app/myroom/[google_id]/_components/BoardModal/BoardModal.tsx
src/hooks/chat/useChatSocket.ts
src/hooks/myroom/useGuestBookGet.ts
src/hooks/myroom/useGuestBookPost.ts

- close #225  
- 방명록 삭제 API 추가
- 한글 채팅 두번 보내지는 버그 해결

✨ Feat(#225): 나의 방명록 삭제 기능 추가

---

public/svg/eraser.svg
public/svg/pen.svg
src/app/layout.tsx
src/app/lobby/_components/Widget/FriendInformation.tsx
src/app/lobby/page.tsx
src/app/meetingroom/[id]/_components/canvas/Toolbar.tsx
src/provider/socket-provider.tsx
src/store/useToolStore.ts

Han seung chan/issue232

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_constant/index.ts
src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
src/app/myroom/[google_id]/_constant/index.ts
src/hooks/lobby/useLobbyRenderer.ts
src/hooks/lobby/useLobbySocketEvents.ts
src/hooks/performance/useLoadSprites.ts
src/store/useUsersRef.ts

🚑️ Fix(#234): 메인 로비 움직임 보간 버그 수정

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_constant/index.ts
src/hooks/lobby/useLobbyRenderer.ts
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersRef.ts

- close #241 
* Throttle 추가하여 delay 추가
* delay시에 시간을 상댓값이 아닌 절댓값으로 비교하여 가속되지 않도록 수정

🚑️ Fix(#241): 메인 로비 움직임 가속 버그 해결

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_constant/index.ts

- close #243 
* 메인 로비 움직임 가속 버그 수정 및 속도 변경

🚑️ Fix(#243): 메인 로비 움직임 가속 버그 수정 및 속도 변경

---

src/auth.ts
src/provider/socket-provider.tsx
src/store/useClientIdStore.ts

- close #240 
- 구글 로그인 후 비회원 로그인 하면 이전 이름 뜨는 버그

🚑️ Fix(#240): 게스트 로그인 버그 수정

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_constant/index.ts
src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
src/hooks/lobby/useLobbyKeyboard.ts
src/hooks/myroom/useMyRoomKeyboard.ts

Fix(#247): hotfix

---

src/app/layout.tsx
src/app/lobby/_components/Npc/NpcModal.tsx
src/components/alertModal/AlertModal.tsx
src/components/gameRuleModal/GameRuleModal.tsx
src/components/modal/MiniGame/MiniGameModal.tsx
src/components/modal/NeedSignIn/NeedSignInModal.tsx
src/components/redundantModal/RedundantModal.tsx
src/hooks/useEscapeKey.ts
src/provider/socket-provider.tsx
src/store/useIsConnectionsStore.ts

- close #246 
- 이중접속 시 모달 띄우기
- esc 키 클릭시 모달 닫힘

✨ Feat(#246): 이중접속 모달 띄우기

---

src/components/chat/left/LeftChatWidget.tsx
src/components/chat/right/RightChatWidget.tsx
src/hooks/chat/useChatSocket.ts

🚑️ Fix:  맥북 채팅 두번 보내지는 버그 수정

---

src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx

- close #233 
- 마이룸에서 API 호출 안되던 버그 픽스
- [] 로컬 작동 확인

🚑️ Fix: 마이룸 API 함수 호출 픽스

---

package.json
src/app/not-found.tsx
src/components/ui/loading.tsx
yarn.lock

💄 Design: 에러 페이지, 로딩 UI 디자인

---

src/app/lobby/page.tsx
src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts
src/app/meetingroom/[id]/page.tsx
src/app/myroom/[google_id]/page.tsx
src/hooks/chat/useChatSocket.ts
src/hooks/lobby/useLobbySocketEvents.ts
src/hooks/myroom/useMyRoomSocketEvents.ts

✨ Feat(#100): 이런저런 내용

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersRef.ts

- close #260 
* 메인 로비 undefinded 버그 수정
* 소켓 패킷 일부 변경

🚑️ Fix(#260): 메인 로비 undefinded 버그 수정 및 소켓 패킷 일부 변경

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/page.tsx
src/hooks/lobby/useLobbySocketEvents.ts
src/store/useUsersRef.ts

🚑️ Fix(#267): hotfix

---

src/app/layout.tsx
src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_components/NoticeBoardModal/NoticeBoardModal.tsx
src/app/lobby/_constant/index.ts
src/app/questmap/_components/RankingModal/RankingModal.module.css
src/app/signin/SignInpage.module.css
src/components/chat/right/RightChatButton.tsx
src/hooks/lobby/useLobbyRenderer.ts
src/hooks/myroom/useMyRoomRenderer.ts
src/styles/font.ts
src/styles/globals.css

- close #272  
- 둥근모꼴 글로벌 폰트 적용
- 네임 태그 (텍스트 백그라운드) 적용
- 게시판 -> 자유게시판으로 이름 변경

💄 Design(#272) 둥근모꼴 글로벌 폰트 적용 및 네임 태그 적용

---

src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
src/app/myroom/[google_id]/_components/TechStackModal/TechStackModal.tsx
src/app/myroom/[google_id]/_constant/index.ts
src/hooks/myroom/useMyRoomRenderer.ts

- close #277 
* 마이룸 기술스택 svg 맵핑 및 화면 랜더링 로직 추가
* TechStackModal에 현재 값을 가져올 수 있도록 로직 추가
* 변경한 마이룸 UI

💄 Design(#277): 마이룸 기술스택 svg 맵핑 및 디자인 수정

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/lobby/_constant/index.ts

- close #283 
* 배포 및 시연을 위해 일단 이전 버전의 움직임 로직(시간 기반 -> 프레임 기반 움직임)으로 변경

🚑️ Fix(#283): 메인 로비 움직임 시간 기반이 아닌 프레임 기반으로 움직이도록 설정 되돌리기

---

src/app/lobby/_components/EnterMeetingRoom/EnterMeetingRoom.tsx
src/app/lobby/_components/EnterMeetingRoom/Room.tsx
src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
src/hooks/myroom/useGuestBookPost.ts
src/queries/myroom/getName.ts

- close #280 
- 미팅룸 누구 방인지 알려주기
- 회의실 누가 접속 해있는지 알려주기
- 포폴 여러개 등록 가능하게
- 포폴 클릭시 새탭

✨ Feat(#280): 기능추가

---

src/queries/myroom/getName.ts

🚑️ Fix: API url 변경

---

src/app/lobby/_components/Widget/FriendInformation.tsx
src/app/lobby/page.tsx
src/components/bgMusic/BgMusicButton.tsx

- close #297 
- 메인 페이지에서 채팅 중일 때 배경음악 토글 버튼 키보드로 실행 불가 처리
- 메인 페이지에서 채팅 중일 때 친구목록 버튼 키보드로 실행 불가 처리
- 메인 페이지에서 채팅 중일 때 z키를 눌러도 친구목록을 열 수 없음.
- 메인 페이지에서 채팅 중일 때 c키를 눌러도 오디오 토글을 할 수 없음.
- 맥 사용자들을 위해 친구목록 열기에 'ㅋ'키 처리 추가
- 맥 사용자들을 위해 채팅 열기에 'ㅌ'키 처리 추가
- 맥 사용자들을 위해 오디오 토글에 'ㅊ'키 처리 추가

🚑️ Fix(#297): 메인 페이지 토글 버튼 단축키 중복 입력 처리 픽스

---

src/app/lobby/page.tsx
src/components/PrefetchManager.tsx
src/hooks/chat/useChatSocket.ts

🚑️ Fix: hotfix

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
src/app/quest/page.tsx

- close #304 
- 포탈 상호작용 시 효과음 볼륨 감소
- `/quest` 페이지 접속 시 용 효과음 볼륨 감소

💄 Design(#304) 포탈 및 용 효과음 볼륨 감소

---

src/hooks/socket/useAudioSocketConnect.ts

Revert "🚑️ Fix: 이전 커밋으로 되돌리기"

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
src/app/quest/page.tsx
src/components/bgMusic/BgMusicGlobal.tsx
src/components/chat/right/RightChatButton.tsx

- close #310 
- 효과음 볼륨 증가
- 'ㅌ'키로 채팅 열 수 있음
- 효과음 볼륨 증가
- 'ㅌ'키로 채팅 열 수 있음

🔨 Refactor(#310): 효과음 음량 조절, 'ㅌ' 키로 채팅 열기 추가

---

src/app/lobby/_components/Canvas/LobbyCanvas.tsx
src/app/questmap/_components/RankingModal/RankingModal.module.css
src/components/PrefetchManager.tsx
src/middleware.ts
src/provider/socket-provider.tsx

- close #이슈번호 
- 로비페이지 소켓연동 안하게 변경
- 프리패치 url 추가
- 모달 색상 변경
- 이동시 채팅창 열었을 때 동작하는 이동 버그 제거
- 미들웨어 코드 제거

✨ Feat(#312): 이런저런 버그 수정

---

src/middleware.ts

🔨 Refactor: 미들웨어 코드 추가

---

src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts

✨ Feat: 캠버스 첫유저 동기화

---

src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts

- close #이슈번호 
- canvas 처음 방문 유저 동기화

🚑️ Fix(#318): canvas 처음 방문 유저 동기화
